# Fifa Soccer Players #

## Import packages and explore dataset ##

In [1]:
import pandas as pd
import plotly.express as px

df = pd.read_csv('fifa_soccer_players.csv')
df.head()

,sofifa_id,long_name,age,dob,height_cm,weight_kg,nationality,club_name,league_name,player_positions,...,defending,gk_diving,gk_handling,gk_kicking,gk_reflexes,gk_speed,gk_positioning,value_eur,wage_eur,overall_rating
0,158023,Lionel Andrés Messi Cuccittini,33,1987-06-24,170,72,Argentina,FC Barcelona,Spain Primera Division,"RW, ST, CF",...,38.0,NaN,NaN,NaN,NaN,NaN,NaN,67500000,560000,93
1,20801,Cristiano Ronaldo dos Santos Aveiro,35,1985-02-05,187,83,Portugal,Juventus,Italian Serie A,"ST, LW",...,35.0,NaN,NaN,NaN,NaN,NaN,NaN,46000000,220000,92
2,200389,Jan Oblak,27,1993-01-07,188,87,Slovenia,Atlético Madrid,Spain Primera Division,GK,...,NaN,87.0,92.0,78.0,90.0,52.0,90.0,75000000,125000,91
3,188545,Robert Lewandowski,31,1988-08-21,184,80,Poland,FC Bayern München,German 1. Bundesliga,ST,...,43.0,NaN,NaN,NaN,NaN,NaN,NaN,80000000,240000,91
4,190871,Neymar da Silva Santos Júnior,28,1992-02-05,175,68,Brazil,Paris Saint-Germain,French Ligue 1,"LW, CAM",...,36.0,NaN,NaN,NaN,NaN,NaN,NaN,90000000,270000,91

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18944 entries, 0 to 18943
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   sofifa_id         18944 non-null  int64
 1   long_name         18944 non-null  object
 2   age               18944 non-null  int64
 3   dob               18944 non-null  object
 4   height_cm         18944 non-null  int64
 5   weight_kg         18944 non-null  int64
 6   nationality       18944 non-null  object
 7   club_name         18719 non-null  object
 8   league_name       18719 non-null  object
 9   player_positions  18944 non-null  object
 10  potential         18944 non-null  int64
 11  pace              16861 non-null  float64
 12  shooting          16861 non-null  float64
 13  passing           16861 non-null  float64
 14  dribbling         16861 non-null  float64
 15  defending         16861 non-null  float64
 16  gk_diving         2083 non-null   float64
 17  gk_handling       2083 non-null   float64
 18  gk_kicking        2083 non-null   float64
 19  gk_reflexes       2083 non-null   float64
 20  gk_speed          2083 non-null   float64
 21  gk_positioning    2083 non-null   float64
 22  value_eur         18944 non-null  int64
 23  wage_eur          18944 non-null  int64
 24  overall_rating    18944 non-null  int64
dtypes: float64(11), int64(8), object(6)
memory usage: 3.6+ MB

In [8]:
teams = df.groupby(['league_name', 'club_name'])

In [9]:
teams

In [10]:
teams = teams[['league_name', 'club_name','long_name','nationality','age', 'overall_rating']]
teams.head()

,league_name,club_name,long_name,nationality,age,overall_rating
0,Spain Primera Division,FC Barcelona,Lionel Andrés Messi Cuccittini,Argentina,33,93
1,Italian Serie A,Juventus,Cristiano Ronaldo dos Santos Aveiro,Portugal,35,92
2,Spain Primera Division,Atlético Madrid,Jan Oblak,Slovenia,27,91
3,German 1. Bundesliga,FC Bayern München,Robert Lewandowski,Poland,31,91
4,French Ligue 1,Paris Saint-Germain,Neymar da Silva Santos Júnior,Brazil,28,91
...,...,...,...,...,...,...
16532,Rep. Ireland Airtricity League,Shelbourne FC,Daniel O'Reilly,Republic of Ireland,25,58
16597,Rep. Ireland Airtricity League,Finn Harps,Barry McNamee,Republic of Ireland,28,58
16818,Rep. Ireland Airtricity League,Finn Harps,Kosovar Sadiki,Canada,21,57
16944,Rep. Ireland Airtricity League,Finn Harps,Sam Todd,Republic of Ireland,22,57
17052,Rep. Ireland Airtricity League,Finn Harps,Mark Anthony McGinley,Republic of Ireland,30,57

In [11]:
df.league_name.value_counts()

English League Championship             709
USA Major League Soccer                 701
Argentina Primera División              659
English Premier League                  654
Spain Primera Division                  645
Italian Serie A                         645
English League One                      630
Spanish Segunda División                619
English League Two                      605
French Ligue 1                          600
Turkish Süper Lig                       589
German 1. Bundesliga                    548
French Ligue 2                          546
German 3. Bundesliga                    522
Japanese J. League Division 1           521
Portuguese Liga ZON SAGRES              510
Mexican Liga MX                         509
German 2. Bundesliga                    507
Belgian Jupiler Pro League              492
Holland Eredivisie                      466
Chinese Super League                    436
Saudi Abdul L. Jameel League            435
Polish T-Mobile Ekstraklasa             426
Romanian Liga I                         425
Swedish Allsvenskan                     412
Norwegian Eliteserien                   403
Campeonato Brasileiro Série A           360
Korean K League Classic                 336
Austrian Football Bundesliga            310
Scottish Premiership                    308
Danish Superliga                        305
Swiss Super League                      266
Australian Hyundai A-League             250
Rep. Ireland Airtricity League          243
Ecuadorian Serie A                      233
Paraguayan Primera División             207
Colombian Liga Postobón                 195
Uruguayan Primera División              178
Liga de Fútbol Profesional Boliviano    174
Chilian Campeonato Nacional             174
Peruvian Primera División               164
Italian Serie B                         154
Venezuelan Primera División             153
Greek Super League                      112
Russian Premier League                   81
Czech Republic Gambrinus Liga            79
Ukrainian Premier League                 56
South African Premier Division           56
Argentinian Primera B Nacional           30
Croatian Prva HNL                        28
UAE Arabian Gulf League                  28
Finnish Veikkausliiga                    25
Name: league_name, dtype: int64

In [13]:
df.long_name.unique()[0]

'Lionel Andrés Messi Cuccittini'